// Generated by https://quicktype.io

export interface Article {
    id:         string;
    title:      string;
    abs:        string;
    n_citation: number;
    authors:    Author[];
    year:       number;
    topn_sim:   Array<number[]> | null;
	score: number;
}

export interface Author {
    name: string;
    id:   string;
    org:  null | string;
}
